### ISSUE TITLE
Avoid to define functions with parameters passed by value

### ISSUE THREAD

**Issue by scalpel4k** [baldapps/artemis#2]
HI,

I think the checker could be a bit smarter. The above is not good advice if the method parameter is of type std::string or any of those smart pointers.

thx Michi

**Comment by baldapps** [comment]
I'm agree however it would be hard to evaluate if the parameter is ok or not. This rule actually has been added because used in old projects where I was involved and it is was used. Really old projects with c++98 style. However today the pass by value is much more common, as you said for smart pointers or to better manage move semantics from c++11. Today this rule is usually turned off for me. Honestly I don't know if it's better to deprecate it or not or maybe an exception list could be added.

**Comment by baldapps** [comment]
Fixed with 2.8.0
